### ISSUE TITLE
Centering scores

### ISSUE THREAD

**Issue by Masclins** [kenan-rhoton/card-game#111]
![board](https://user-images.githubusercontent.com/7271634/38802970-15468ed6-416e-11e8-81ba-ef26d5360ba1.jpg)

EDIT:
**Opponent's card's** was solved with a minor change.

The row-scores should be centered. Right now the innerHTML there seems to ignore any attempt to center them.

**Comment by Masclins** [comment]
I leave this issue oppened for centering the scores, though I'll change the title and description

**Comment by Masclins** [comment]
Now it's changed, but was wondering if you'd prefere another way to show scores:
![img](https://user-images.githubusercontent.com/7271634/38994964-0fc08742-43e8-11e8-8b09-0089bc2165f8.jpg)

**Comment by kenan-rhoton** [comment]
the first one's fine, for now
