### ISSUE TITLE
Optimize victory_conditions

### ISSUE THREAD

**Issue by Masclins** [kenan-rhoton/card-game#126]
Right now `rules/victory_conditions.clj` does what is supposed to do, but in a really innefficient way (it calculates the scores of every row twice, and recurs among all cards four times).

It would be nice to optimize this functions, since they are checked after every play and could potentially make everything slower.

**Comment by kenan-rhoton** [comment]
Is this still necessary? I feel it's no longer as inneficient, other than rows being checked twice (but changing that I feel will require a bunch of code to generate a state for a row that says which player, if any, is winning).

I would say we could do this *very slight* optimization, but only if it ever becomes a bottleneck (or if someone is very bored)

**Comment by Masclins** [comment]
Closed since it seems as no longer necessary.
