### ISSUE TITLE
Frontend needs urgent Styling to be useable

### ISSUE THREAD

**Issue by kenan-rhoton** [kenan-rhoton/card-game#13]
Frontend "works" but cannot reasonably be used by a human.

This would be fixed by:

- Applying CSS styles to frontend/src/views and components or,
- More likely: importing [Bootstrap](https://getbootstrap.com) in Frontend/public/index.html and using Bootstrap classes to make everything nice in the components and views.

**Comment by Masclins** [comment]
I've no idea on how to do that.
Even though, if nobody can handle this issue I'll assign myself to it and learn CSS and whatever Bootstrap is.

**Comment by kenan-rhoton** [comment]
Go for it if you want, but I can take it unless @pernilsalat wants it.
