### ISSUE TITLE
Use a tool for cleaner code

### ISSUE THREAD

**Issue by Masclins** [kenan-rhoton/card-game#131]
I think it'd be a good idea to use  Codacy, Codefactor and/or a similar tool to ensure having a cleaner code and finding potential problems.

I use them both for signepedia and seems useful.

- [x] Clojure
- [x] Javascript / Node.js
- [ ] Other (pug, bash, Dockerfiles...)

**Comment by kenan-rhoton** [comment]
You set up Codacy for this, right?

**Comment by Masclins** [comment]
I did, but wasn't sure if everybody saw it or only me (since I'm not the admin of the project).

Also, can everybody see the Codacy reported issues? ( https://app.codacy.com/app/masclins/card-game/issues/index )

If so, this issue can be closed.

**Comment by Masclins** [comment]
...I just realized that Codacy doesn't analyze Clojure (nor Leiningen)...

I'll look for another one and unset Codacy for this project.

**Comment by Masclins** [comment]
It seems like github offers no tool for Clojure :(

Even though, there seems to exist Eastwood that can be used. It won't be integrated into github, but can be runned once in a while, or even be included in Docker or Travis, so it is somewhat automatized and we always have a file with the errors...

**Comment by kenan-rhoton** [comment]
I can add `lein-cloverage` to Travis, I believe. I would make it a separate step so we're always clear on failure reason.

**Comment by Masclins** [comment]
@kenan-rhoton if you include Codacy as a hard(ish) requirement to accept a PR, this Issue will be solved.

**Comment by kenan-rhoton** [comment]
Closing due to Codacy and all the other actions taken so far.
