### ISSUE TITLE
Abilities as functions

### ISSUE THREAD

**Issue by Masclins** [kenan-rhoton/card-game#149]
After discussing about how to handle new card abilities we realized that Clojure gives us the opportunity to use functions as an attribute of cards.

We should make cards have (when appropiate) abilities as functions that are called when played.

That would give us a lot of flexibility on what cards can do.

**Comment by Masclins** [comment]
The backend already handles abilities (the only one we have) as a function.

Now we have the issue of how to pass it to frontend, since it'll be crazy it frontend recieves a function.

Since all ability functions have to be called with `game-state` (at least one variable) I'd make that calling an ability function with no paramaters returns the description needed for frontend.
If so, what you think about returning the name of the ability followed by parameters needed?  For a card with *add-power 3*, frontend would recieve `:ability ["add-power" 3]`

**Comment by kenan-rhoton** [comment]
I think all frontend needs to know is whether a card requires a target or not, righit? Maybe some ability text if you want to inform the player.
