### ISSUE TITLE
New ability: Card power modified depending on the row

### ISSUE THREAD

**Issue by Masclins** [kenan-rhoton/card-game#150]
We will include a new rule:

Cards might have different values on certain rows.

My idea is to give rows the attribute `:type "row's type"`. Some cards might have abilities that change their power depending on row's type.

**Comment by Masclins** [comment]
I'm willing to solve this as follows:

- Rows can have *type*
- Cards can have an ability that changes its power when played on a row with a specific *type*.

It's explained on the [Manual](https://github.com/kenan-rhoton/card-game/wiki/0.-Troll:-Card-Game-Rules)

**Comment by kenan-rhoton** [comment]
I agree with this approach

**Comment by Masclins** [comment]
Trying to write this ability down I realized the function needs to know which card has the ability and on which row will be played.
On the other hand, `add-power` needed only the target.

To avoid having to pass different arguments to every ability, it seems the wisest would be always passing `game-state` and `play` (a single play, the one that triggered the ability)

**Comment by kenan-rhoton** [comment]
that seems quite sensible, really, then it wouldn't even need a target
