### ISSUE TITLE
Backend passes abilities info to frontend

### ISSUE THREAD

**Issue by Masclins** [kenan-rhoton/card-game#154]
**Description of the current (after #152) situation**

Card abilities are functions. That makes it impossible for frontend to understand what the ability does and therefore what it should show or ask the player.

**Description of the wanted situation**

Abilities functions can be called with no argument. That returns a definition (map?) that can be handled by fronted and gives information about what to show and what to expect.

For *add-power +3* ability I was thinking about something like that:
For backend, card would have: `:ability (ability/add-power 3)`.
For frontend, card would have: `:ability {:add-power 3 :targets 1}`. That gives information on the ability and it's *related attribute*, as well as how many targets it should expect.  

**Considered alternatives**

I think we should pass the number of needed targets too. Maybe we could make it somehow different, like `:ability {:add-power 3} :needed-targets 1`.

Options that put all the ability on a string or let the frontend decide if the player must choose a target seem too much work for the frontend (extreme case would be `:ability "add-power-3"`)

**Additional context**

It's probably impossible to choose the *best* option when we don't know yet what kind of abilities we'll have, but I'd want to give the most importance to:

- Keeping it the most flexible.
- Avoiding as much work from frontend as possible.

We won't be able to make any e2e advance if we don't solve this. If and when we merge #152 e2e communication will be broken until we solve it.

**Comment by kenan-rhoton** [comment]
As I mentioned on the other issue, I think we should just inform frontend of whether or not a target is needed and maybe some ability text (just a string) to explain to the player what the ability does.

**Comment by Masclins** [comment]
Could you write an example of what you think we should return to frontend?

I think that something among the lines of `:ability "add-power-3" :targets 1` can be a problem, since we'll need to take `"add-power"` and `3` from the string to show it properly.

**Comment by kenan-rhoton** [comment]
I was thinking straight up something like: `:description "Enhance 3" :targets 1`.

Frontend doesn't actually need to know that a function called `add-power` exists.

**Comment by kenan-rhoton** [comment]
This would either imply cards having some "text" attribute or having a database where we store info for each card (which seems premature)

**Comment by pernilsalat** [comment]
I think i am not getting what you say, so i will explain what i think will be a fine solution:

When the api gives you a card, it have an attribute called `abilities: [String, String, ...]`. the name of the ability matches a function in the front-end-abilities-pool that ends with a fetch to the correct end-point ability, with always need the index of the card that makes the ability, and other things that will get defined.

I don't see why this communication should be with more than one POST, but as i said at the begging, i am probably missing something.

**Comment by kenan-rhoton** [comment]
Frontend *never* needs to know what an ability does. It just represents the state visually. All the logic is done in backend. If we erode this separation we will have problems in the long run...

**Comment by pernilsalat** [comment]
Yes, the function pool in the front end only would have the data gathering that the backend needs

**Comment by kenan-rhoton** [comment]
I meant there is no need for there to even be a frontend function pool... it literally just needs a text to show and whether or not a card needs a target.

**Comment by Masclins** [comment]
Frontend only needs to know if a target must be chosen by the player, and what to show so the player knows what the card will do.

`:description "Enchance 3"` could be directly printed unto the card and the player would know what the card will do.
`:target 1` will let frontend know 1 target is needed, and ask the player to choose it.

(therefore, I agree with the alternative by @kenan-rhoton )

What's wrong with this approach, @pernilsalat?

**Comment by pernilsalat** [comment]
I don't see how front will be able to display the visuals with only this, how does front know if it is damage? buff? Therefore i don't thinks it is a good solution.

At the very least the response should contain a `:type "damage"`, and target should specify if allies, enemies or all

**Comment by kenan-rhoton** [comment]
Right now we don't distinguish. Adding a distinction further on will be trivial.

Therefore I invoke YAGNI (You Aren't Gonna Need It) and say we don't need to implement things we may never use.
