### ISSUE TITLE
Clarify next-play

### ISSUE THREAD

**Issue by kenan-rhoton** [kenan-rhoton/card-game#16]
Add a visualization for the next-play (probably by putting a different background color on the card or outline or something).

Right-now there is no indication that you even made the play correctly.

**Comment by Masclins** [comment]
Writing the status somewhere would be useful too ("Play a card" or "Wait for your opponent's play")

**Comment by Masclins** [comment]
I see two ways to do that:

- Adding something like `:status "next-play"` on cards to be played on backend
- Checking `:next-play`. If doing the second, shouldn't frontend only recieve the index of the card?

Either way it doesn't seem like a *frontend-only* issue.

**Comment by kenan-rhoton** [comment]
I feel like the second option is better: backend already gives enough information for what we need.

And agreed that frontend should only receive the index and only if the `:next-play` is his.

**Comment by kenan-rhoton** [comment]
I also think this and #35 should be done together.
