### ISSUE TITLE
API documentation

### ISSUE THREAD

**Issue by pernilsalat** [kenan-rhoton/card-game#160]
**Description of the current situation**
Right now, anyone trying to work with the front-end part will have to annoy the back guys or know clojure and the back-end project itself just to know the endpoints and responses

**Description of the wanted situation**
A Documentation page/s of the endpoints, http methods that accepts and the possible responses and a brief description if it's not evident

**Comment by Masclins** [comment]
I totally agree that having this would make everything easier. I'd love being able to have this documentation that would let us to work better together while I do backend and you frontend.

Problem is that I have no idea on how a good API documentation must be... Any help with that?

**Comment by Masclins** [comment]
I'm really willing to do this Issue, but I'd need some guidelines on what would be a good API documentation for our project.

**Comment by kenan-rhoton** [comment]
A good API should indicate:

1. What endpoints the API responds to (POST /games/, GET /games/:game-id/player/:player-id, etc.)
2. The accepted formats for the request
3. The response format

All formats should be annotated with the types of the data, as well as conditions that need to hold.

However, if we truly implement Pact, the Contract will be the best documentation, and we might even be able to just generate the documentation from there.

**Comment by Masclins** [comment]
Migrated to https://github.com/doner-kebard/card-game-backend
