### ISSUE TITLE
Server crashes due to messages/invalid-target not existing

### ISSUE THREAD

**Issue by kenan-rhoton** [kenan-rhoton/card-game#166]
**Description**
The backend server crashes upon starting due to `messages/invalid-target` not existing.

**To Reproduce**

Execute `lein ring server` from the `backend` folder.

**Expected behavior**

The server starts normally.

**Additional context**

`messages/invalid-target` does not exist in the config nor do any tests check for it. Both these problems should be adressed.

**Comment by Masclins** [comment]
On develop, this message is defined at `configs/config.yml` and `backend/src/configs/messages.clj`
Also, there's a test at `test/rules/play_card_test.clj:90`.

I close this bug as invaled. If there's a branch where this error happens, it should be solved simply by updating with develop.
