### ISSUE TITLE
Fix warnings on frontend unit-tests

### ISSUE THREAD

**Issue by kenan-rhoton** [kenan-rhoton/card-game#17]
Some weird warnings which I have no clue about their source when running the `yarn test`.

**Comment by Masclins** [comment]
Where can I find the `yarn test`?
The only warning in front-end tests I got is on `JoinGame.spec.js`. Docker says `1 warning potentially fixable with the '--fix' option.`. Is that the warning? Maybe we should try that? (don't know where I'm supposed to use `--fix`)

**Comment by kenan-rhoton** [comment]
`yarn test` is just how you execute the frontend tests *once* (`docker-compose run frontend yarn test`) as opposed to on-change (`docker-compose run frontend yarn test -w`), which is really the same thing.

The warnings given are (other than the silly `JoinGame.spec.js` one you mentioned which **should be fixed** as a part of this):

### App
```
[Vue warn]: Unknown custom element: <router-view> - did you register the component correctly? For recursive components, make sure to provide the name option.

(found in <Root>)
```

### MainView

```
[Vue warn]: Unknown custom element: <router-link> - did you register the component correctly? For recursive components, make sure to provide the "name" option.

(found in <Root>)
```

They are probably both related to the fact that I don't really know what I'm doing when it comes to `router` ¯\\_(ツ)_/¯

**Comment by Masclins** [comment]
Warnings seems to be solved by including 
`import router from "@/router";
import Vue from "vue";

Vue.use(router);`
on *App* and *Main* tests.

But that causes a new error on *Game* and *Join Game*.
Probably this helps:

> Hi, this is a common problem with trying to set $route or $router when it's already been installed on the base Vue contstructor. Somewhere in your code you will be calling Vue.use(VueRouter).

You need to only install on a localVue, otherwise $route and $router are added as read-only properties to the base constructor, and you'll be unable to rewrite them.

**Comment by kenan-rhoton** [comment]
Ok, try the following:

1. Undo the changes to App and Main
2. Instead, pass the following as a second argument to `shallow(`:

For App.vue:

```javascript
{ stubs: { 'router-view': { render: h => h("div") } } }
```

For MainView.vue:

```javascript
{ stubs: { 'router-link': { render: h => h("a") } } }
```
