### ISSUE TITLE
Clean up Game component

### ISSUE THREAD

**Issue by kenan-rhoton** [kenan-rhoton/card-game#19]
Clean up the `frontend/src/components/Game.vue` component in frontend (probably into different Hand and Board components), cause it does way too many things already (essentially does the whole game itself)

**Comment by pernilsalat** [comment]
Mine! an easy one to start..

**Comment by kenan-rhoton** [comment]
I think maybe Game.vue should actually be a view with Hand, Board and Scores as its components maybe?

I sorta had it like that at first but I'm not very clear on how to organize the different vue components.

Any suggestions appreciated, @pernilsalat

**Comment by kenan-rhoton** [comment]
This is done as a side effect of #49
