### ISSUE TITLE
Backend periodic errors need fixing

### ISSUE THREAD

**Issue by kenan-rhoton** [kenan-rhoton/card-game#20]
Fix random backend periodic errors (NullPointer Exception in responsify within api_handler.clj:41).

No clue on source or what is going on, it doesn't seem like `responsify` could *actually* be causing them...

**Comment by Masclins** [comment]
I can't get this error.
Do we have any idea *when* it happens?

**Comment by kenan-rhoton** [comment]
It's possible this is already fixed by some previous changes, will check again and close the issue or give reproduction steps.

**Comment by kenan-rhoton** [comment]
Ok, can no longer reproduce, closing.
