### ISSUE TITLE
General backend structure cleanup

### ISSUE THREAD

**Issue by kenan-rhoton** [kenan-rhoton/card-game#26]
We need to clean up the backend project structure.

In particular I'm worried about:

- *API*: I think we should split `api.clj` into two files (with one of them only containing the actions directly reference in `api_handler.clj` and the other containing the "helper" functions. In any case, I think they should be in a subdirectory and all be contained within a `card-game.api.*` namespace.
- *Tests*: Seriously, `api-test` and `core-test` are both over 150 lines. Also the `(defexpect' groupings are kinda random. We need to restructure the tests to be more clearly focused on different functionalities by file. Also, "API" is not a functionality, it's just an interface...
- *Core*: I think we should also split up this file but I'm unsure how.
- *Build Card*: We should burn this with fire. Both the tests and its functionality and replace it with whatever it does. I don't know what I was smoking to think it was necessary for some reason.

**Comment by Masclins** [comment]
I'm thinking about creating the file `src/configs.clj` that will include:
- Initial hand for both players (both number of cards and which cards)
- Error and status specific messages

Also, I'd like to split (considering your request) `src/api.clj` into `src/api_base.clj` and `src/api_helper.clj`
The first will have functions `create-game`, `add-player`, `play-card-as-player` and `get-game` (the only ones used on `src/api_handler.clj`. The rest will go the `src/api_helper.clj`

I'm not sure about `src/build-card`. Right now cards are pretty basic, but they could get way more complicated. If you *really* feel like it should removed, explain a bit more how and why, please. The reason I somewhat like it is that in the future a card will be able to have many weird attributes, and its builder can help making its creation easier to call.

**Comment by kenan-rhoton** [comment]
Ok to the `src/configs.clj` idea.

About the splitting, I would take it *further* and make an `api` directory within `src/card_game/` which would contain:

1. `src/card_game/api/base.clj` with a namespace of `card-game.api.base`
2. `src/card_game/api/helper.clj` with a namespace of `card-game.api.helper`
3. `src/card_game/api/handler.clj` with a namespace of `card-game.api.handler`

Keep in mind this will entail changing all references to them to referencing the new namespace. In particular, change the `project.clj` reference to the current handler entry-point to use the new namespace or everything will crash on `docker-compose up` 🙃
