### ISSUE TITLE
UpdateGame Interval is never killed

### ISSUE THREAD

**Issue by kenan-rhoton** [kenan-rhoton/card-game#31]
Ok, this mistake is the cause of #28 and #20. It's also stopping #13. In fact, it's a miracle we've even had ANY passing Travis builds with this thing.

In `frontend/src/components/Game.vue` we have this near the end:

```javascript
  created: function() {
    this.updateGame();
    setInterval(
      function() {
        this.updateGame();
      }.bind(this),
      1000
    );
```

This makes the browser poll the `this.updateGame` once per second but this is NEVER KILLED. It would normally be killed when the browser leaves the page, but since the Vue router abuses the `#` on the URL, you technically never leave the page.

We need to make sure the function *can be killed* and *is killed* whenever we navigate away from the page via router.

This is done via `beforeRouteLeave` as described in https://router.vuejs.org/en/advanced/navigation-guards.html

**Comment by pernilsalat** [comment]
try this:

```
created: function() {
    this.updateGame();
    this.intervalID = setInterval(
      function() {
        this.updateGame();
      }.bind(this),
      1000
    );

beforeRouteLeave: (to, from , next) {
  clearInterval(this.intervalID);
}

```
