### ISSUE TITLE
Playing cards by clicking

### ISSUE THREAD

**Issue by Masclins** [kenan-rhoton/card-game#35]
Right now cards can only be played by dragging them onto the boardgame.
They should be playable *also* by clicking them and then clicking on the row.
That would imply marking them while they are "selected" (Probably should be worked with #16, for using an outline in both cases, but with different color).

**Comment by ruchnar** [comment]
I don't know how to implement this with clojure, but there should be an :on-click function... somewhere...

**Comment by Masclins** [comment]
This is *forntend-only* so nothing needs to be done in clojure.
