### ISSUE TITLE
Limited number of cards per player on rows

### ISSUE THREAD

**Issue by Masclins** [kenan-rhoton/card-game#42]
We want to be able to limit the number of cards each player can play on each row.

To begin with, rows should have a limit of 4 cards per player.
This number must be easy to change and make it different for each row.

**Comment by kenan-rhoton** [comment]
It will be *very* important to decide on how the backend will communicate an attempt to play a card illegally on a "full" front (which until now was not possible).

**Comment by kenan-rhoton** [comment]
I mean it wasn't possible to make an illegal play other than playing out of turn.

**Comment by Masclins** [comment]
It would be lovely to have the row greyed and dragging a card there would simply made nothing.

**Comment by kenan-rhoton** [comment]
Agreed for frontend visualization, but remember that backend must enforce *all* the rules by itself, even if frontend can "cheat" and know some of them (although in my opinion, that should be kept to a minimum).

**Comment by Masclins** [comment]
Many tests regarding victory conditions will need rework, since now they abuse being able to play as many cards in a row as wanted to end the game.

**Comment by kenan-rhoton** [comment]
The end to end tests will have problems as well, but it is, I believe, a *very* valuable rules change 🙃

I think having at least two people tackle this issue together might be beneficial when we get to it.

**Comment by pernilsalat** [comment]
For the front visualization is a good solution what @Masclins  said.
But as @kenan-rhoton  said, we need to see the bigger picture.  I can give a possible approach:
The api should have an abstraction of the game played, and the client should request:

- Request the initial hand
- Move the N card of my hand to the X row and the Y position (like coordinates)
- Abilities to display (this is a 2 way communication, the client can give details about the targets of some ability once the client know what ability)
- Update info to show in the board when a card is played
- End game/round or similar

The player drags 

- the card from his hand to the desired row
- On release, the client sends a request to move the card: is the response is 2XX the action is done, and if not the card goes back to the player hand

If the user cheats,  he will only cheat his browser, and actually he will lose a card or an ability, so only bad things for the cheater ;)

**Comment by Masclins** [comment]
I'd try to avoid penalizing *cheaters* when the cheat could come from a bug on that specific browser.

**Comment by pernilsalat** [comment]
There is no way for us to know if it is a bug or a cheat

**Comment by Masclins** [comment]
But we can simply avoid either of those change the game-state, don't we? I mean, rather than making him lose a card or an ability.

**Comment by pernilsalat** [comment]
The api needs to protect itself from the client. If you wanna repeat the process till the client gives a valid imput this will give too much room for weird things to happen. I think that is much safer and beneficial tu just end that action

**Comment by kenan-rhoton** [comment]
Right now, my vision for the `backend` vs `frontend` is:

- `backend`: provide a game-state through `GET /games/:game-id/player/:player-id` and through nowhere else, allow actions performed by the player through a JSON payload sent by `PUT /games/:game-id/player/:player` to modify the game-state or not according to the game rules.
- `frontend`: Present the most user-friendly possible way a player can interact with the `backend`.

So `backend` enforces all rules, if you play a card with a certain ability, the next game-state you retrieve will just have the **resulting** state, not the process.

However, the `frontend` will have the card data from `game-state`, so that means if frontend wants to present a certain animation or whatever when the `PUT` does not return an error, everything is cool.

**Comment by ruchnar** [comment]
I don't see why we can't always check the condition in both frontend and backend, the non-cheater user will receive a message from frontend telling him that he is playing the card in a wrong place. Then we will have to deal with the cheater user at the backend. This will reduce the load of traffic and processing in the server.

**Comment by kenan-rhoton** [comment]
That can be part of *presenting the most user-friendly interface possible*, since it would be faster. And sure, my definition is slightly reductionist, diminishing the load on the server is a good idea.

But we should in no way **ever** just trust that frontend will validate stuff. That leads to bugs and security issues.

**Comment by Masclins** [comment]
Should the limit be a property of the `:rows` in a `game-state`? Or one of the `game-state`?

So it could be,
`(:rows-limit game-state) => [4 4 4 4 4]`
or
`(:rows game-state) => [{:limit 4 :cards []} {:limit 4 :cards []} {:limit 4 :cards []} {:limit 4 :cards []} {:limit 4 :cards []}]`

**Comment by kenan-rhoton** [comment]
I feel the most flexible approach would be having it inside the `:rows` themselves but having a function `(defn set-global-row-limit` which sets them all to a certain number (since initially we want all of them to have the same limit)

**Comment by Masclins** [comment]
I think this will be long... but let's go!

**Comment by kenan-rhoton** [comment]
Godspeed!

**Comment by kenan-rhoton** [comment]
It would be sensible to split this issue into multiple ones, probably, to make life easier for everyone and avoid one giant pull request

**Comment by Masclins** [comment]
Maybe beginning with the backend part only...?

**Comment by kenan-rhoton** [comment]
This is not a backend-only issue, but you may create a separate issue linked to this one which only touches the backend parts 😄

**Comment by Masclins** [comment]
I thought we were going to split this in minor issues.
Are we?
As I see it, there are the following sub-Issues:
1. Being able to configure a row limit (backend)
2. Giving an error when a card is player on a row that already has reached its limit (backend)
3. Not letting any card to be played beyond the limit (frontend)
4. Showing the row limit for each row (frontend)
5. Configuring the row limit and avoid it is a problem for tests not related to it (backend and frontend)

**Comment by kenan-rhoton** [comment]
Split it! 😄

**Comment by Masclins** [comment]
Everything we wanted regarding row limits for v0.2.0 had already been done.
