### ISSUE TITLE
Centralize our configuration

### ISSUE THREAD

**Issue by Masclins** [kenan-rhoton/card-game#43]
To follow DYR, most (if not all) error and status messages are on `backend/src/configs.clj` (maybe it should be nested somewhere else?)

There are still some of those hardcoded on `frontend/test/unit/Game.spec.js` (lines 16, 26 and 29).
(I couldn't find any other case where that happens)

Those should make reference to what's on `backend/src/configs.clj`.

**Comment by Masclins** [comment]
As per #44 configs should be on different files, in `backend/src/configs/`.

**Comment by Masclins** [comment]
How is this an "enchancement"? Isn't it a problem that a file doesn't do what it's supposed to do? (In this case: `configs/messages.clj` including all the messages to DRY and letting us change those)

**Comment by kenan-rhoton** [comment]
Bug: Something isn't doing what we programmed it to do.
Enhancement: We want our program to reflect new design decisions.

**Comment by kenan-rhoton** [comment]
I've run into a little issue that we should all be aware of, and which I hadn't thought about:

1. Config shared between `backend` and `e2e` is solved
2. However, having `frontend` have access to `config` means that it will be 100% public (as the file will get loaded by the browser).

This shouldn't be at all a problem, but we should all be aware that anything in the config file will be considered 100% public.

I'll put a comment to remind us of it at the top.

**Comment by Masclins** [comment]
It should have access to certain files on `config`, not all of them.
Right now, only `messages.clj`.
