### ISSUE TITLE
File reorganization

### ISSUE THREAD

**Issue by kenan-rhoton** [kenan-rhoton/card-game#44]
Ok, I think we need to reorganize and clarify the project structure, this is what we currently have:

- **backend**
    - **doc**: why does this even exist?
    - **src**: Where the backend production  code lives
        - **card_game**: Where the backend production code lives, except configs.clj for some reason.
            - **api**: Were we define how frontend or any other client can communicate with the system
    - **test**: Where the backend test code lives.
        - **card_game**: Where the backend test code lives.
- **e2e**: Where the end-to-end tests live.
- **frontend**
    - **public**: Where the... um... index.html lives?
        - **img**: Images?
            - **icons**: icons?
    - **src**: Where the frontend javascript production code lives.
        - **components**: Where the javascript... components... live?
        - **views**: I give up, what's the difference, again?
    - **test**: Where the frontend tests live.
        - **unit**: Where the frontend unit tests live

I feel like we could do much better and have a clearer organization with something like:

- **backend**
    - **src**: Where the backend production code lives
        - **rules**: Where are the rules logic lives (currently "core")
        - **api**: Where we define how frontend or any other client can communicate with the system
        - **persistence**: Where we define how we store persistent data
        - **configs**: Where we load our configuration
    - **test**: Where the backend test code lives.
        - **api**: Api tests
        - **rules**: Rules tests
- **e2e**: Where the end-to-end tests live.
- **frontend**
    - **static**: Where static stuff (images, stylesheets, whatever) lives.
    - **src**: Where the frontend production code lives
        - **lobby**: Where all the Game Creation/Game Joining logic lives
        - **game**: Where the actual gameplay occurs
    - **test**: Where the frontend test code lives
        - **lobby**: Where we do all the lobby tests
        - **game**: Where we do all the game tests

Any thoughts or ideas? This would be a pretty big change, and since it is about understanding the system and having everything in a clear place, I would like *everyone* to say something about it 🙃

**Comment by Masclins** [comment]
I like that.
Still we should wait until we close the #39 pull-request that also changed organitzation, shouldn't we?

Configs would be a directory with multiple config files on it (probably clearer)?

**Comment by kenan-rhoton** [comment]
This would be post #39, yes 🙃

**Comment by Masclins** [comment]
I'll begin working with the backend of this, waiting for #39 before touching any affected file by that pull-request.

When that's done, if nobody begun with front-end, I'll do it too.

**Comment by kenan-rhoton** [comment]
We should wait until input from @pernilsalat, mainly dependant on whether he's already started splitting Game or not

**Comment by kenan-rhoton** [comment]
Nevermind, thought this was the #45 Kill Vue with fire, issue, carry on

**Comment by Masclins** [comment]
After seeing the files we have, I will wait:
- I'll begin backend reorganization when #39 is merged
- I'll begin frontend reorganization when #45 is closed.

**Comment by Masclins** [comment]
Regarding backend:

1. `doc/intro.md` has any function? Could it be removed?
2. I have no clue what `target/` does. Should we keep it here?
3. `Dockerfile` and `project.clj` should be kept here?

**Comment by Masclins** [comment]
Also, regarding backend and its namespaces.

Right now most of the `(ns` begin with `card-game.`. Should we keep it this way? Should we remove all those `card-game.`? I assume we will change the `core.` for `rules.` but I'm not sure about the `card-game.` part because now they are not into `card-game/` (because it no longer exists) but the project is called `card-game` (in `project.clj`, `(defproject card-game`)

**Comment by kenan-rhoton** [comment]
- The entire `doc` should be removed.
- `target` is already ignored by git (notice it's not in the repo) due to being in `.gitignore`, it's just a folder where Clojure compiles the code to run it
- `Dockerfile` and `project.clj` should be at the root of their section (so `/backend/` in this case, exactly where they are now)
- We should definitely remove the `api_` from the tests once they're in a `api` folder.
- With my proposed changes, there will not be any more `card-game` in namespaces. The project name as far as I know is purely aesthetic.

**Comment by kenan-rhoton** [comment]
frontend done in #49

**Comment by kenan-rhoton** [comment]
@Masclins you want to reopen this, I assume?
