### ISSUE TITLE
Kill Vue with fire

### ISSUE THREAD

**Issue by kenan-rhoton** [kenan-rhoton/card-game#45]
It's an unnecessary dependency in our project (caused by me) that provokes:

1. Weird frontend structure
2. Less intuitive and readable code in the frontend
3. Less flexibility to do things like #44 
4. No great advantage (it does provide some) to making our game better

We should instead apply the same philosophy we do to backend: no new dependencies until it's absolutely unavoidable, and attempt to keep everything as clean, organized and simple as possible.

If we do this, we'll have to stop and close all frontend issues to undertake this, and it would be a team effort (I can split the tasks among different issues).

It would have the added benefit that if we all actually work on the frontend base, we'll better understand it, especially if we try to avoid "magic libraries" for as long as possible.

**Comment by Masclins** [comment]
Agree. Let's begin working on this asap

**Comment by kenan-rhoton** [comment]
I would also reevaluate the need for Bootstrap, we can accomplish the same with plain CSS Grid, I think
