### ISSUE TITLE
Mantain the Game Manual

### ISSUE THREAD

**Issue by Masclins** [kenan-rhoton/card-game#46]
We need to have a clear Game Manual.
This must be a document explaining the rules in a clear and easy to understand way, that encompasses any possible game situation.

This manual is on the Wiki (https://github.com/kenan-rhoton/card-game/wiki/0.-Troll:-Card-Game-Rules). 
It is **very important** that **everybody** reads it (otherwise I can't see how any rule can be correctly implemented). Also, any opinion regarding how to organize it or its clarity will be very well recieved.

**Comment by Masclins** [comment]
I changed the title to represent that this issue is probably never going to be closed, at least while we keep adding new rules.

I'd keep the issue open to comment anything regarding the Manual.

**Comment by Meal88** [comment]
We need a game start section in the manual that defines how the rows are chosen and set, and which cards are gonna be in your hand.

**Comment by Masclins** [comment]
We need to update the Manual to include two new "rules".
- Row limit per player: A player cannot play a card on a row on which he already has that many cards.
- Change value: Some cards choose another card in the board when being played, and change the value of that card.

This is only to explain what needs to be included, not how it should be. Also, rule 4.1 needs clarifying.

Can you handle that, @Meal88? Maybe @ruchnar could help with this?

**Comment by Masclins** [comment]
This Issue includes working on the format and structure of the Wiki of Lenses so it can be used quickly and efficiently.

**Comment by Masclins** [comment]
I **completely** remodeled the Game Manual, since it didn't need to be that complex.

**Comment by kenan-rhoton** [comment]
Completely agree with the restructuring
