### ISSUE TITLE
New function needed: get-total-points

### ISSUE THREAD

**Issue by ruchnar** [kenan-rhoton/card-game#47]
Right now, under /backend/src/card_game/victory_conditions.clj we have these two functions: 

get-points -> Tells how many points each player has on each row
most-points -> Tells which player has the most points

We need to add another one as a step to solve the issue #18 . 

The function should be named "**get-total-points**", it should return the number of rows won for each player (eg the number of points for each player), and it should be placed between **get-points** and **most-points**.

Also, we should change how **most-points** is coded in order to re-use the content of the new function and simplicity.

**Comment by kenan-rhoton** [comment]
Well then! Get on it! 😉
