### ISSUE TITLE
No limits on playing or seeing cards in backend

### ISSUE THREAD

**Issue by kenan-rhoton** [kenan-rhoton/card-game#5]
Right now there is no hard limit that disallows you playing a card despite your opponent haven't played (or even despite not having an opponent yet).

It would be nice to implement:
1. You don't see your cards until an opponent joins with [(add-player](https://github.com/kenan-rhoton/card-game/blob/master/backend/src/card_game/api.clj#L53)
2. Whenever you play a card, you opponent doesn't see it until he himself [plays a card](https://github.com/kenan-rhoton/card-game/blob/master/backend/src/card_game/api.clj#L37) (for simultaneous turns)
3. You cannot play a card after playing a card already, unless your opponent has already played the card (and therefore you see both cards now on the row).

Number **3** in particular will be hard because some current tests *abuse* the fact that you can do it and will have to be rewritten.

**Comment by Masclins** [comment]
Point 2 solved by chaning logic. Cards are only effectively played (through `apply-play-card`) when both players had made their play.

**Comment by Masclins** [comment]
Point 3 is solved in `core.cj` but not in `api.cj`. Game doesn't accept another play until last turn is solved. Still, player can make h

**Comment by Masclins** [comment]
Point 1 solved by adding `:status` to the game-state returned by `get-game`. Client should show a loading screen when `:status` is `"Waiting for Opponent"`.
