### ISSUE TITLE
Cards divided by owner on the backend

### ISSUE THREAD

**Issue by Masclins** [kenan-rhoton/card-game#52]
Right now, on the backend cards of both players are put on the same vector, regardless of their owner (using the attribute `:owner`).

On frontend we already want them divided by owner.

For Issue #42, we will want to know how many cards each player owns on each row. I think that, before addressing that it is interesting to divide rows like we do on frontend.
Right now rows are: `[[] [] [] [] []]`, i propose `[[[] []] [[] []] [[] []] [[] []] [[] []]]`
I think such change will make all functions that need to know the cards of a single player way more readable.

**Comment by kenan-rhoton** [comment]
If we're splitting it up, another option is `[ [[] [] [] [] []] [[] [] [] [] []] ]`

It depends on what will we care most often about, which row (independently of player) a card is in, or which player owns the card.

I don't care either way, just pointing it out 🙃

**Comment by Masclins** [comment]
Most probably I was just willing to change many things on the code to, in the end, avoid creating a function that returns what I want...

I'll close this Issue that I should never have opened.
