### ISSUE TITLE
Improve E2E test coverage

### ISSUE THREAD

**Issue by kenan-rhoton** [kenan-rhoton/card-game#53]
Right now our E2E tests cover what I think is sufficient for the `lobby` parts, but way less than ideal for the game itself.

Right now we have a single Game test called "Sample Game" which simulates a draw by playing on the same row with each player constantly.

At the very least we need tests that simulate a victory for each player.

This will also require extracting much of the test logic into independent functions (which is a great thing).

**Comment by Masclins** [comment]
I don't see myself doing this issue.
I say so because soon it will be the only one left for Release v0.2.0

**Comment by Masclins** [comment]
This should be either closed or edited. There will be no e2e tests to improve after #157

**Comment by kenan-rhoton** [comment]
Closed as irrelevant
