### ISSUE TITLE
Cards in hand identified by independent index

### ISSUE THREAD

**Issue by Masclins** [kenan-rhoton/card-game#55]
We are changing almost everything (mostly backend) so we have an array of all the cards (therefore, identified by an independent index). Cards in this array will have an attribute showing the zone in which the card is. That means a change from "Zones with cards" to "Cards in zones".

Everything from `backend/src/rules` is already changed, including tests.
`backend/src/api` needs to have the tests changed so they use the format "one-test-file-per-src-file".
Now the following needs to be done:

- [x] Double-check backend tests (and add any that's needed/missing)

- [x] Tests for `api/base.clj`: Put the current ones together.

- [x] Tests for `api/base.clj`: Test `(play-card-as-player`

- [x] Tests for `api/conversions.clj`, `api/generators.clj` and `api/handler.clj`. This should be pretty easy, since most of those don't do much.

- [x] Adapt all tests on `backend/old_tests/` (this should be covered by the previous two points, but just in case...)

**Comment by kenan-rhoton** [comment]
Giving cards an `id` field?

**Comment by Masclins** [comment]
Yes. 

And I assume it would be best if it's different for every card (so no shared `id` between my cards and my opponent's)

**Comment by kenan-rhoton** [comment]
Should be assigned on game creation then

**Comment by Masclins** [comment]
I'd like to hear from @pernilsalat and what advantages this would have, before begining working on it.

**Comment by kenan-rhoton** [comment]
Right now zero, it will probably be useful in the future (especially if we want to allow a player to reorganize cards in his hand in frontend). Wait, **I** assigned this to v0.1.0? Woah, I must've been drunk.

**Comment by Masclins** [comment]
Thinking about Issue #41 it would probably be useful to have cards identified by id, also in the board.

**Comment by kenan-rhoton** [comment]
Yes, as card move zones they should keep their id.

**Comment by Masclins** [comment]
It seems like we are working on targets before giving id to cards. 
Do we really want `:target` to be a path, rather than an `:id`?

**Comment by kenan-rhoton** [comment]
I know I don't 🙃

**Comment by Masclins** [comment]
`:target` has been implemented to be a path (shouldn't be hard to change).

The thing is... Knowing the `:id` of a card is easy, while knowing it's path is not that easy (specially when frontend will have to tell backend its path).
On the other hand, finding where a card that has to be changed, based on `:id` might be hard, while doing so with path is easy.

I'd like frontend to have the easiest job here. Therefore, I'd definitely go for `:id`, knowing that we'll need a function to translate an `:id` to a path.

**Comment by Masclins** [comment]
After @pernilsalat suggesting again to use id's in order to solve the problems seen in #119, I reopen this issue.

**Comment by Masclins** [comment]
After doublechecking #122, almost everything is done on backend.

I'll be double-checking the `rules/`, @kenan-rhoton, would you mind changing the tests for the `api/`?

From here, @pernilsalat you should be able to work on frontend.

**Comment by kenan-rhoton** [comment]
I am first priorizing the server and travis, then I'll get on this ticket

**Comment by Masclins** [comment]
I begun the required changes on the branch mod-new-paradigm.

**Comment by kenan-rhoton** [comment]
If you've done a relevant change (such as grouping the test) can you please issue the pull request already and merge to develop? We should merge quick and small changes often, rather than big merges whenever possible

**Comment by kenan-rhoton** [comment]
Currently taking a look at the missing files to determine the needed tests

**Comment by kenan-rhoton** [comment]
- `api/handler.clj` is just interfacing with Compojure and Cheshire (our server and JSON libraries, respectively), so testing it would be testing those libraries which we can safely assume work correctly.
- `api/generators.clj` is just a randomness provider, which just uses `java.util.UUID/randomUUID`, so nothing to test.
- `api/conversions.clj` on the other hand does logic to translate between the internal rules `player-id` and the tags the players actually get to prevent them from knowing their opponent's session ID, and thus should be tested.

**Comment by kenan-rhoton** [comment]
Soooo... this is funny, `conversions` is no longer used anywhere, it's just legacy stuff, I'm deleting it :upside_down_face:
