### ISSUE TITLE
A Wiki of Lenses Formatting

### ISSUE THREAD

**Issue by Masclins** [kenan-rhoton/card-game#56]
Right now I'd been putting the answers we gave to the lenses on the Wiki (https://github.com/kenan-rhoton/card-game/wiki/A-Wiki-of-Lenses)

It would be great to:

- Find a way to capture the most important things on the main page (rather than having to go to every Lens' page to know it)
- Be sure the format is appealing to everyone. For every game design duscussion all *discussers* should be taking the discussed lens into account.
- Translate everything to english (wouldn't it?)

**Comment by kenan-rhoton** [comment]
I can take care of translation if wanted.

**Comment by Masclins** [comment]
Migrated to https://github.com/doner-kebard/card-game
