### ISSUE TITLE
Scores on each row

### ISSUE THREAD

**Issue by Masclins** [kenan-rhoton/card-game#58]
Now that we show the number of rows won, it would be great to show how many points each player has on each row.

It would be great (not sure if it should be another Issue) to also visually show who's winning for each row, maybe by highlighting his number (and the same for the number of rows won).

**Comment by kenan-rhoton** [comment]
This will not go on any current milestones, but if anyone wants to do it, feel free.

**Comment by Masclins** [comment]
After playing (against myself) I feel like the scores part is necessary for having useful feedback from playtesting.

Otherwise it feels more like "who gets tired before of adding numbers"

(maybe we could put the highlighting part into another Issue and work only with the scores for v0.2.0)

**Comment by kenan-rhoton** [comment]
Ok, adding to milestone

**Comment by Masclins** [comment]
Why Issues are now longer auto-closed?

**Comment by kenan-rhoton** [comment]
You have to write "solves #58" in the pull request *description* not the title
