### ISSUE TITLE
Fix rows not being "cleared"

### ISSUE THREAD

**Issue by Masclins** [kenan-rhoton/card-game#59]
On `board/board.js`, `setBoard(boardState)` we clear all rows before putting all cards on each row again.

Problem is that actually this process of cleanings seems to not work.
```javascript
gameRows.forEach(function (gameRow) {
    console.log("cleared")  //Added to see that it actually never entered here
    helper.clearChildren(gameRow);
})
```

**Comment by kenan-rhoton** [comment]
I'm marking this urgent and taking this on before config.
