### ISSUE TITLE
Creating an AI

### ISSUE THREAD

**Issue by Masclins** [kenan-rhoton/card-game#64]
I think it would be great to have an AI asap for two reasons:

1. At some point we will probably want to create one anyway, for single-player experience

2. To find best strategies. Right now we don't have neither enough players nor time to really find the best strategies. That means that almost surely we will miss huge balance issues, or always-winning strategies. Having an AI will help a lot in finding those strategies and see what rules need to be tweeked.

**Comment by kenan-rhoton** [comment]
An AI would have to be a separate (automated) program which interacts with the backend, it shouldn't be a part of the backend itself

**Comment by Masclins** [comment]
Migrated to https://github.com/doner-kebard/card-game
