### ISSUE TITLE
Backend: Improve tests

### ISSUE THREAD

**Issue by kenan-rhoton** [kenan-rhoton/card-game#80]
I've realized many backend tests have more dependencies than needed (`effects_test` really does NOT need to call `create-game` for anything) as well as some that can simply be greatly improved in style and clarity.

It would help a lot to have another pass and maybe establish concrete guidelines for unit tests.

**Comment by Masclins** [comment]
All tests improved, right? Shall we close this Issue?

**Comment by kenan-rhoton** [comment]
I would do one last cleanup pass, I think some helper functions are no longer called, lol.
