### ISSUE TITLE
Mantain the Wiki of Lenses

### ISSUE THREAD

**Issue by Masclins** [kenan-rhoton/card-game#86]
We need to keep track of our discussions regarding Game Design.

Right now this is being done on the Wiki (https://github.com/kenan-rhoton/card-game/wiki/A-Wiki-of-Lenses).

It's very important to have the document updated and easily referenced, so we can check what we decided when working on new aspects of the Game Design.

**Comment by Masclins** [comment]
This Issue includes working on the format and structure of the Wiki of Lenses so it can be used quickly and efficiently.

**Comment by ruchnar** [comment]
I'll leave this here for later review.

https://bugherd.com/blog/building-a-better-github-wiki/

**Comment by Masclins** [comment]
Migrated to https://github.com/doner-kebard/card-game
