### ISSUE TITLE
Backend api should give descriptive errors

### ISSUE THREAD

**Issue by kenan-rhoton** [kenan-rhoton/card-game#97]
Backend should return messages with errors and their causes, such as "invalid id" or "game does not exist".

Especially bad are the cases where an invalid format is used, as an exception is thrown (which is incredibly ugly) and I'm not even sure what the response is in those cases.

Errors to implement:

- [x] A player plays a card that's not on her hand.
- [x] A player makes a play involving a card that doesn't exist.
- [x] A player makes a play involving a row that doesn't exist.
- [x] Player-id or Game-id doesn't exist.

**Comment by Masclins** [comment]
Also: "this is not your card", "this row/card doesn't exist", etc.

It'd be a good idea to make a list of things that should return an error message so we can work on them one at a time.
