### ISSUE TITLE
Backend test cleanup 2: Electric Boogaloo

### ISSUE THREAD

**Issue by kenan-rhoton** [kenan-rhoton/card-game#98]
So I've been giving this a lot of thought and... we're "overtesting".

What I mean is, we have tests that check our rules (in `tests/rules`) and then we have tests for our api which don't really check the api but check the internal functions and make sure they "fulfil the rules".

This is bad, we're testing the same things twice and that is why we have "duplicated" tests within `tests/rules` and `tests/api`.

The rules tests are well done, but the api tests should actually:

1. **USE** the API (that means call into `handler/entry` with an URL and a GET, POST or whatever request)
2. Just test that the calls go as expected and that they communicate with the game rules.

How do we do this, well, for step 1 I've started doing this:

```clojure
(defn request [resource method & params]
  (json/parse-string
    (:body 
      (handler/entry {:request-method method
                :uri resource
                :params (first params)}))
    true))
```

Which can be called by `(request "/games" :post)` for example to issue a "Create Game" action.

For step 2, we would need to mock out the rules we expect to be called and then `expect` them to have been called in the way they should.

This would greatly reduce the amount of tests in API, while actually *increasing* our coverage (which I'm going to also add metrics for).

Thoughts? 🙃

**Comment by Masclins** [comment]
Thoughts:

1. We keep adding new Issues to Release v0.1.1 only because one Issue is taking way longer than expected. If that Issue were resolved on time (being *on time* when it was said to be resolved) there's no way this Issue got into Release v0.1.1. Aren't we abusing of that milestone? 

2. Backend tests need a cleanup for sure, maybe even a restructure. It's hard to find where a function is tested and to decide where to nest a new test.

3. Most of the tested `api` functions do much more than simply calling a `rules` one. Could you give an example of something checked twice due to a `rules` and `api` test?

4. Still, though, it seems like a good idea to simplify most of the `api` tests by checking their answer to a request. In the end, that's what we want.

**Comment by kenan-rhoton** [comment]
1. Agree
2. Agree
3. I'll give an example in short
4. Agree

**Comment by kenan-rhoton** [comment]
An abstract example: everything that uses `autoplay/as-api` is actually simulating a game and thus, the rules. A more simple approach would be to mock a finished game (one without hands) and simply make the call for the status and check that the scores or whatever are correct.

A concrete (and different) example:

```clojure

(defexpect playing-cards
  (let [game (api/create-game)
        game-id (:game-id game)
        player-id (:player-id game)
        opponent (api/add-player game-id)
        opponent-id (:player-id opponent)]
    ; Cards in hand have power
    (expect
      #(empty? (filter (fn [e] (nil? (:power e))) %))
      (:hand game))

    ; Card is not removed if opponent has not yet played
    (expect
      #(= (count (:hand %)) (count hands/default-hand))
      (do
        (api/play-card-as-player game-id player-id 0 0)
        (api/get-game game-id player-id)))

    ; Cards are removed from hands upon both having played
    (expect
      #(= (count (:hand %)) (dec (count hands/default-hand)))
      (api/play-card-as-player game-id opponent-id 0 1))

    ; card played is owned by self
    (expect
      #(= :me (get-in % [:rows 0 0 :owner]))
      (api/get-game game-id player-id))

    ; opponent's card is owned by him
    (expect
      #(= :opponent (get-in % [:rows 1 0 :owner]))
      (api/get-game game-id player-id))))
```

These are basically just repeats of the tests in `test/rules/play/`, as the comments indicate.

**Comment by kenan-rhoton** [comment]
I just realized this issue is practically necessary to be able to do #97, So I'll do them together.
